### PR TITLE
added interactive viz and shiny lessons

### PR DESCRIPTION
**Pull request by vpnagraj**

### CODE REVIEW

**Comment by stephenturner** [comment]
Before I pull in changes, could you update your `tibble` and `dplyr` packages, then clean and rebuilt the site? When I'm looking at the diffs I'm seeing a bunch of instances where it looks like you've built the HTML with older versions, which, among other things, result in slightly different printing of data frames, e.g.

```
 # Optionally, bring up the data in a viewer window
  # View(ydat)</code></pre>
 -<pre><code>## # A tibble: 198,430 x 7
 +<pre><code>## Source: local data frame [198,430 x 7]
 +## 
  ##    symbol systematic_name nutrient  rate expression
 -##     &lt;chr&gt;           &lt;chr&gt;    &lt;chr&gt; &lt;dbl&gt;      &lt;dbl&gt;
 +##     (chr)           (chr)    (chr) (dbl)      (dbl)
  ## 1    SFB2         YNL049C  Glucose  0.05      -0.24
 -## 2    &lt;NA&gt;         YNL095C  Glucose  0.05       0.28
 +## 2      NA         YNL095C  Glucose  0.05       0.28
  ## 3    QRI7         YDL104C  Glucose  0.05      -0.02
  ## 4    CFT2         YLR115W  Glucose  0.05      -0.33
  ## 5    SSO2         YMR183C  Glucose  0.05       0.05
 @@ -446,7 +453,8 @@ <h1 class="title toc-ignore">Data Manipulation with dplyr</h1>
  ## 8   VMA13         YPR036W  Glucose  0.05      -0.75
  ## 9    EDC3         YEL015W  Glucose  0.05      -0.24
  ## 10   VPS5         YOR069W  Glucose  0.05      -0.16
 -## # ... with 198,420 more rows, and 2 more variables: bp &lt;chr&gt;, mf &lt;chr&gt;</code></pre>
 +## ..    ...             ...      ...   ...        ...
 +## Variables not shown: bp (chr), mf (chr)</code></pre>
  </div>
  </div>
```

**Comment by stephenturner** [comment]
Also, any idea why this line seems to be removed from the resulting HTML files?

```
-<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />
```

**Comment by stephenturner** [comment]
actually, not sure that adding font-awesome to the site_libs is necessary. It looks like it's already being pulled in via the CDN on line 90:

https://github.com/bioconnector/workshops/blob/53cd06d12d30e3bd5251644519e9e2ac6ffc48af/_site.yml#L90

Just wondering why it got removed from the resulting HTML files in your fork. I'll see if I can figure out.

**Comment by vpnagraj** [comment]
cool ... i've built the site with the newest versions of dplyr and tibble installed ... and i'm not totally sure what's going on with the missing font awesome css but maybe has something to do with the htmlwidgets / js that i'm calling in the interactive viz lesson?

https://github.com/rstudio/rmarkdown/issues/742

in any event, i've added the missing line to the _include/in_header.html file that's reference in the _site.yml ... seems to be dropping that link into the header of the html files now

**Pull request merged**
