### PR TITLE
Bonus problem solution

### PR DESCRIPTION
**Pull request by RomeroBarata**
Hello,

I've noticed that the current solution to the bonus problem is making comparisons between distinct countries. For instance, row 13 (Albania 1952) is being compared to row 12 (Afghanistan 2007) and then being incorrectly included in the answer. Also, it is assuming that the data are ordered by countries and years (indeed it is, but it is not safe to assume so).

In this patch I propose a solution to both issues.

Kind regards,
Romero Morais

### CODE REVIEW

**Comment by stephenturner** [comment]
Thanks @RomeroBarata. Would you mind updating your fork and making the change to [r-dplyr-homework.Rmd](https://github.com/bioconnector/workshops/blob/master/r-dplyr-homework.Rmd)? There's a merge conflict now, as #30 split out the homework assignments from the main lesson. 

Also copying @vpnagraj on this. This question resulted in some confusion and ambiguity every time we've covered it. I believe you end up getting different answers depending on whether you include both filtering conditions in the same function with an `&` operator, versus two separate filtering statements with one `%>%`'d to the other, and the result changed depending on how you set this up. Was this still an outstanding issue?

**Comment by vpnagraj** [comment]
@stephenturner yep i think that was the one that we had issues with last time around ... @RomeroBarata good eye and thanks in advance for the fix

**Comment by RomeroBarata** [comment]
No worries @stephenturner and @vpnagraj , I'll update my fork and submit the correction!

Btw, thanks for the tutorials, they're great!

EDIT: All good now =D

**Comment by stephenturner** [comment]
big thanks @RomeroBarata

**Pull request merged**
